---

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/SpecialGlobalVars:
  Enabled: false

Style/RescueModifier:
  Enabled: false
