language: ruby
rvm:
- 2.3.0
- rbx-3.14
bundler_args: "--without lint --jobs=3 --retry=3"
cache: bundler
gemfile: gemfiles/Gemfile.ci
before_install:
- gem update --system
- gem install bundler
script: bundle exec rake ci
matrix:
  include:
  - rvm: 2.2
    gemfile: gemfiles/Gemfile.doc
    script: bundle exec rake yard:deploy
    env:
    - DOCS=true
sudo: false
env:
  global:
  - secure: eYfZEZYiVMyeIJ9r3jAxgtF9vXDO2jMMJok9PL5tkKIDdi5XmkF2V1cwzzLI69DAPwuhfkPWVbiDgqjD0OHexOJMYipmdpgoZ/2AsSDnbzUDAbfuxjhGCvghD80U4lvb9B/VYWxhcubTsUXjBaivaik859wmajqLi0ROwD3jgm/0AF5oXpyHiIqEkFxQJ7E8D2pUm9kx4IH9uTP+lqrzBOdto2aGc+8XqgewcImC5Qp5ycikbZyPpvEKQDRYp6dHpcInrj+6TpiGW/HCs7R/Luf7BUILIgrV3NT4eFeGRvhdk2ON2v84ke0O8FDtrGje9uQWVn/dT2jL6wAekUyxS5CW225DzKjA6IIr54nQDizFjduFNPFDN4xWZr33e6EfWKe8uAJTOMepCVJ5Gr3jeGkT3xn8VXZLwZ0OZJ4BuKWzDcQqQZd0EQWKhOlhtm32jJ+YrSBWX4tLl8ma9qCLSy2dVKd5qVjIvX221Pg/rsGwO1MpNnV0OL3QUihKQxHPFbL/NNTGkGFnL/lMN85OdPXm6lmPYFS09GUYRYty7zOmBmQI53w7vsIxXjTKxE42od6smvWm3yicH/EKXzHcGmepPDILBWjazEsuXwvAi21y66fOTl1hWPE26+y9UWWmUEPU4uEq1oEFSjrM7qPhc1ZnLNUCY1gSFxQ5KCU1bXc=
  - secure: awIPy+jkMz4xhU/hxMjWV5Qbbt/uoYrPgUmklHWUvqtl2IkL6DkPlPrPbT2ZYLwkThlSmZvZ4enbXECIKUKsSz42S8bw0IjKCyEWuWSD/e8BZhCouZF8MEoj6sowOj9Pkwko6M9DUFwISYRy8RGHaYbzIPoSpaCbIhqUGu86EM6f02VZ87sFe9dNAKK/m2FfC2boeq2W1oN/oOcm7dKaFVMxRYRxHrEaPKObtte9hhqh7oZPNmCCciPYYi4JwfSJuLDLwZhRNJz76UI1Jd8YVei4TKIJjQma2YS/AE7YfIEpTSPUuaSdu1shwk4hh9PmRO8QItTPx0HaBrC+UAXe2MlBgjO6Rz4wzVM8lp1XAI+zYGADUDy5FuzjoWXnSDrBjizryOPL8DleNpXjgsyQecAAQPyqrsLTtNfeB61Rcs09LGzI9olrxE84hazYvXhZNtuBCINowiSpKCcQvKuYBVucIQgTf3YvX5XKAvCJ5IqJUyCuU3KgGy5qq/6ChF10Pt+iyullgsJdABWDIvtQrwdsMp4kF2bgizZXA37GAEW6egEx+QJddUo1LUXoENP3+Zxqb+lUqD+NU49h2sEuZApCp1afz0D7dZ4YQuLaRv5cf7ncyxNAE1EHfdtBsur1XxWLbuUJd3upaycT14NukOXctTzfjH6XCy0uXFzsA78=
  - secure: FUe2u7TbT5d/aSZtGJkWuQt15p4fmSSW1dQM7yAAJN/7P/AJ5wetpSJxqfoiQ4/ETYS5mwY5rrfunP+BH+ijsr/n0Ovkc2+fQnW6xvv1oBwRWM/mhOEqHlSX3W7wOgQ5sTR5qbee5227OXQVR4NnIIpDbhErM+zsidTwIM7zSr/MLnHjIaFqHcOs6O81o1raWuMleqXl79gFBM8NAQDsHeQDNnc/1aSwPr/ahoWnTvFQz9MvJm8plQmBXJaPDSX2Ty6aaafTTImukdINnpPdo6tu3YoYY46MHASt7rjKPgWKqhlq8xGPY03Pcs6AVcVNmZ+jrG/q/JIT4TVJnJjThHE/8w1jOtD2pbsE5RTIzEZMLcRXbx9pKZGfKdCarOZPpIapm7lMqryMMZx7qHSbLgu/KtVMzGNFYPiPFAE1K3shNSsvCs0deJ8JsDTSU/y+S35rFRk0hJ4dR8GiDLAu9ykqDLMWy4ApQ4488ysRhI4oUyTFYWQF5aKH1mWsMwgksS1GJycJxEKrca8kCWs0sjPRHVjVMn8ISzp+tTs9QiVujjm5Is+T0TXlhVIDLdYHXpiQYFlqyyS5mAOMAqLKITaEaYwi9k+GkWjl3GeUirG+9bmuZpI5aXhR8+SxKpHCLySiWJU1NUk9N084tU0rgMGN1znNSx7dv17Q7FXzFMw=
